name: CodeCanvas Scanner

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: write
  contents: read
  pull-requests: read
  
jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install @octokit/rest

      - name: Fetch and run checkLogic.mjs
        run: |
          curl -O https://raw.githubusercontent.com/Abdulnaser97/CodeCanvasScanner/main/main/checkLogic.mjs
          node checkLogic.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
